services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: osman728
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      DATABASE_URL: postgres://osman728:nest123@db:5432/mydb

volumes:
  pgdata:
